### ISSUE TITLE
Backtesting code error - no 'modules.isolation_model' found

### ISSUE THREAD

**Issue by datatalking** [RomanMichaelPaolucci/Q-Fin#1]
I'm enjoying your [Medium article](https://towardsdatascience.com/a-quick-and-easy-way-to-build-and-test-stock-trading-strategies-bce2b58e6ffe) and have implemented the code but its giving errors.

Are these suppsed to be part of one huge class or is there a function not included? I've expanded upon your [code in my repo here for](https://github.com/datatalking/Financial_Backtrader) reference since I didnt see it in yours. Thanks for writing these articles they are good reference material.

```
box/PycharmProjects/Financial_Backtrader/backtesting_b.py", line 3, in <module>
    from models.isolation_model import IsolationModel
ModuleNotFoundError: No module named 'models'
```

https://github.com/datatalking/Financial_Backtrader/issues/1

**Comment by romanmichaelpaolucci** [comment]
Hi Andrew, I'm glad you find my articles useful.  Please note that QFin is not built to contain the 'models' module you are attempting to reference.  What you are trying to implement is an example of a prop model used to execute trading decisions.
