### ISSUE TITLE
Negative Put Prices

### ISSUE THREAD

**Issue by micycle1** [RomanMichaelPaolucci/Q-Fin#2]
The library produces negative prices for put options having small delta. Calls don't have this behaviour (price tends to zero, as expected).

i.e compare:
```
BlackScholesCall(4600, 0.19, 4400, float(5)/365, 0.01).price # 201.4
BlackScholesPut(4600, 0.19, 4400, float(5)/365, 0.01).price # -190.6
```
or see (where price and delta columns are derived from q-fin `BlackScholesPut`)

![image](https://user-images.githubusercontent.com/9304234/198678749-9d682a20-e12c-4b4a-83b5-1c850881232a.png)

I'm wondering what I should make of this -- whether there's an error with the library, or a quirk of BS model (in which case I can take a floor of zero of put price value).

**Comment by micycle1** [comment]
I've just tried the same with `py-vollib`. The price seems more normal, indicating a bug with q-fin.

![image](https://user-images.githubusercontent.com/9304234/198681350-dc5b9468-c078-44f5-b88a-6920239a836f.png)

**Comment by romanmichaelpaolucci** [comment]
Hey there thank you for raising this issue!  The library was using d2 and d1 backward for Black-Scholes puts, rolling out an updated version of QFin fixing this now!
