### ISSUE TITLE
Problem with the Geometric Brownian Motion Code from YT video

### ISSUE THREAD

**Issue by DJRKM** [RomanMichaelPaolucci/Q-Fin#3]
I get the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [19], line 1
----> 1 sample_paths = geometric_Brownian_motion (S_0, mu, sigma, T, dt, n)

Cell In [17], line 13, in geometric_Brownian_motion(S_0, mu, sigma, T, dt, n)
     10     prices.append( prices[-1]*np.exp((mu - .5*(sigma**2))*dt + sigma*np.random.normal(0, np.sqrt(dt))))
     11     time += dt
---> 13 if T (time) > 0:
     14     prices.append(prices[-1]*np.exp((mu - .5*(sigma**2))*(T-time) + sigma*np.random.normal(0, np.sqrt(T-time))))
     16 paths.append(prices)

TypeError: 'int' object is not callable

under the following code:
sample_paths = geometric_Brownian_motion (S_0, mu, sigma, T, dt, n)

**Comment by DJRKM** [comment]
[Untitled1 - Jupyter Notebook.pdf](https://github.com/RomanMichaelPaolucci/Q-Fin/files/10102864/Untitled1.-.Jupyter.Notebook.pdf)

**Comment by romanmichaelpaolucci** [comment]
Hey there!  You need to specify "T - (time)" as you are decrementing the total number of discrete steps from the horizon T.

If you are interested in simulating GBM more concisely try using QFin!  QFin has a vectorized GeometricBrownianMotion class that you can pass those parameters to in the constructor to yield your sample paths.  

If you have any more questions feel free to email me: roman@quantguild.com always happy to help!
